Add telemetry events
microsoft/MSIX-PackageSupportFramework pull request #229
Opened 2023-02-13 13:19 UTC by npuvvada

More telemetry events are added

2023-02-16 02:30 UTC, rahul89dadhich requested changes
please check comments

2023-02-16 02:30 UTC, rahul89dadhich commented on PsfRuntime/Config.cpp
> +    TraceLoggingWrite(
Can we have difference message to identify the difference between both ?

2023-02-16 02:30 UTC, rahul89dadhich commented on fixups/DynamicLibraryFixup/DynamicLibraryFixup.cpp
> +                        "Exceptions",
why we are having same logging messages?

2023-02-16 02:30 UTC, rahul89dadhich commented on fixups/EnvVarFixup/EnvVarFixup.cpp
> +                    "Exceptions",
Same message content

2023-02-16 02:30 UTC, rahul89dadhich commented on fixups/RegLegacyFixups/RegistryFixups.cpp
> +                                    "Exceptions",
same as previous, please check fix all, if required

2023-02-16 18:23 UTC, dhoehna commented on include/psf_constants.h
> +    constexpr wchar_t current_version[] = L"1.0.221230.1";
Big possibility for this number to not be updated during a new release.  Connect with the Windows App SDK folks to figure out how they managed this.

My suggestion is to change this number to a constant local copy.  Something like 0.0.05.  Then, during the official build, replace this value with the correct version.

2023-02-16 18:26 UTC, dhoehna commented on PsfLauncher/PsfPowershellScriptRunner.h
> +			TraceLoggingWideString((&script == &(this->m_startingScriptInformation)) ? L"StartScript" : L"EndScript", "ScriptType"),
I don't see any documentation about adding new TraceLogging calls to new fixups.  I suggest to add documentation on where, and how, to add traces.

2023-02-20 06:39 UTC, rahul89dadhich approved these changes
looks good

2023-02-21 17:39 UTC, dhoehna commented
Looks good. :)

2023-02-22 14:21 UTC, merged